color: null
fieldLayouts:
  ebab32af-963b-4677-9318-eda2779b8fda:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-17T20:37:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3fda0030-420c-4c1b-a703-98db3b8c8b2f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:27:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c65be2cf-aeb9-4056-b998-39b6312f91a1 # Texte
            handle: textImageEditor
            includeInCards: false
            instructions: null
            label: Éditeur
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e86bf72c-6a52-40d8-b03b-4c8d5e78f141
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:27:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 14cc298d-f39c-448c-8dbb-1c4a52ec18db # Link
            handle: textImageLink
            includeInCards: false
            instructions: null
            label: Bouton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b068fdd1-097e-4974-9204-30dde7216b70
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:27:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d529af64-31d5-47b9-a37f-5218bab2e1f5 # Image
            handle: textImagePicture
            includeInCards: false
            instructions: null
            label: Photo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc2d482b-4874-4c86-a823-2c769173db87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:27:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4ee6553-c48d-4ca6-bb21-6c841b59efe2 # Positionnement de l’image
            handle: textImageAlignment
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf5f5e93-b066-4fe7-8b21-90cac5ae4124
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e24bbdb-588b-476d-a152-f693f3f21492
        userCondition: null
handle: blockTextImage
hasTitleField: true
icon: null
name: 'Texte et image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
