color: null
fieldLayouts:
  acc5b063-c8cb-4e47-b5da-20c6a3eabf98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-17T20:47:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 965504bd-026f-44c9-920a-6110b8df1b81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:59:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b89fdecb-83bc-41bb-8331-c442f9ec9281 # Documents
            handle: documentationFiles
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f125111-fc82-486e-a528-b85228bcfaca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:59:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ced25593-9a15-4f62-944f-75a5e88cf204 # Liens
            handle: documentationLinks
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e1c5fa-84fd-46bd-976a-7d3d2fadc06c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b313e369-bf20-4e47-955d-089be4a5a3c5
        userCondition: null
handle: blockDocumentation
hasTitleField: true
icon: null
name: 'Documents et liens'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
