color: null
fieldLayouts:
  bec4391d-765e-416c-a8a4-e61ceac4e7aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-17T20:42:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3899b44a-d395-4e5a-9dc2-dca6ac79bd58 # Type de galerie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac19fbc7-c245-40c3-b6b8-a64f2aca2c27
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-17T20:26:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 338a0cfd-d28c-48df-af36-e552a8f2df81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T20:42:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a61e898b-80d6-44b1-9f22-2f51b72df97e # Images
            handle: galleryImages
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7f915ea-db65-43dd-a282-6f6a601090dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52e1bba2-4869-4e4a-ba43-d9122a333832
        userCondition: null
handle: blockGallery
hasTitleField: true
icon: gallery-thumbnails
name: Galerie
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
