color: null
fieldLayouts:
  951ab1e5-1104-4bf2-9865-ff6b97df7844:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-29T14:44:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ce45d59-56c6-4a65-bcdb-774911cf3f63
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T17:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 99ff4ecb-263e-465c-885f-78119bc0d93d # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66aebfb4-b2b6-47b1-a82e-39617290953d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-16T21:12:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 498ba9f8-9fae-4a65-b67d-9a8251c3abc9 # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 717364d1-28bf-41da-91af-72d183fd15db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T17:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1e13e9d6-7ea5-47b0-9e9f-6d806576c40d # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1ee9d76-54e3-4612-950e-837b72b26010
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T17:26:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c65be2cf-aeb9-4056-b998-39b6312f91a1 # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b912340-9429-460d-8435-1535fb0661b7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T17:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0e249ad1-b8eb-46f3-9896-4df70db56f5c # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65d5212c-0f69-43bd-85eb-09cf84bd4dbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-30T17:24:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 14cd5d53-35a9-4b02-a1e4-5ff467c3fa53 # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a68b91a-7db9-41fd-b93d-b63bb950f1cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T19:53:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ba5f6d4f-75bf-453d-9b0d-76017e4e4dee # Contenu modulaire
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64875bf9-93dd-4d77-b7ff-dde6adbbbb5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7abbcba8-bce4-4025-b979-a02336ca0dd2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-29T14:46:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f193a844-47c9-4aaa-ad8e-874278f2aa52 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 323c54a1-6908-4975-b0c7-88d7c18ac091
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-29T14:46:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1dd4cca-7af1-45f3-976b-18be012e7aad # SEO Open Graph Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 095e4dd3-c198-4ed4-bb23-ea0751c5931e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3f34c7a9-4af5-4c4f-bfb6-31a4aa09c8ff
        userCondition: null
handle: default
hasTitleField: true
icon: null
name: 'Pages par défaut'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
