color: null
fieldLayouts:
  ff36c0f0-9689-407a-a318-aa0b034e55ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-28T19:45:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ade72b1e-5f62-4f2e-84c0-6b7db889d294
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47ef1fd5-8df6-4e86-8c8e-9c759ae2b4a4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-28T21:23:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f193a844-47c9-4aaa-ad8e-874278f2aa52 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cbbc21f-bfce-4c8e-b00d-452329fa8856
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-28T21:23:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e1dd4cca-7af1-45f3-976b-18be012e7aad # SEO Open Graph Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72552275-45d2-4d4e-9de2-9b63b6057526
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 19ef0108-ce7c-405b-8e0d-515657b8ee9a
        userCondition: null
handle: singleHome
hasTitleField: true
icon: house
name: Accueil
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
