color: null
fieldLayouts:
  0cd96bdf-9d28-48bb-bdd5-4d0b9e929c20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-17T19:13:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titre
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: babba11c-82ae-458e-a230-9a5a4c5fb6f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T19:16:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1e13e9d6-7ea5-47b0-9e9f-6d806576c40d # Texte
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57ca3072-d2fd-47e0-82b0-3dcb347e7556
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-17T19:16:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 14cc298d-f39c-448c-8dbb-1c4a52ec18db # Link
            handle: null
            includeInCards: false
            instructions: null
            label: Bouton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95151f39-c3fd-4fa7-9c74-5592edf89a0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cea20499-278c-48b5-8497-05a87a15fa84
        userCondition: null
handle: structureCta
hasTitleField: true
icon: null
name: 'Appel à l’action'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
