headingLevels: false
name: Extra-light
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        defaultValue: false
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - bold
  - italic
  - superscript
  - subscript
  - link
  - specialCharacters
  - nbsp
