altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  a3305f71-c091-4eb5-a271-40d781a0bb30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-27T16:09:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ab4865f8-c8b1-4cb5-ab64-3c3670ef1266
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea94e3d3-ad55-400a-a452-7d3c57133aba
        userCondition: null
fs: fileSystemsImages
handle: volumeImages
name: Images
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: fileSystemsAssetTransforms
transformSubpath: images
