columnSuffix: null
handle: sharedLinks
instructions: null
name: Liens
searchable: false
settings:
  addRowLabel: 'Ajouter un lien'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Texte du lien'
            -
              - handle
              - linkText
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Lien
            -
              - handle
              - linkUrl
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Nouvelle fenêtre'
            -
              - handle
              - linkTarget
            -
              - width
              - ''
            -
              - type
              - lightswitch
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
