columnSuffix: null
handle: sharedUrl
instructions: null
name: 'Lien externe'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
