columnSuffix: null
handle: sharedMinimalistText
instructions: null
name: Texte
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
