columnSuffix: null
handle: sharedExtraLightText
instructions: null
name: Texte
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  ckeConfig: df41c4cb-d63a-4ac7-89a6-3f7a6f8d0483 # Extra-light
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
