columnSuffix: null
handle: sharedMediumText
instructions: null
name: Texte
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 81dca28e-68dc-4e2f-b181-1c4ac16d2abb # Medium
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
