columnSuffix: null
handle: socialMediaLinks
instructions: null
name: 'Médias sociaux'
searchable: false
settings:
  addRowLabel: 'Ajouter un média social'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Libellé
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Lien
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Icône
            -
              - handle
              - icon
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Facebook
                    -
                      - value
                      - facebook
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Instagram
                    -
                      - value
                      - instagram
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - YouTube
                    -
                      - value
                      - youtube
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - LinkedIn
                    -
                      - value
                      - linkedin
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - TikTok
                    -
                      - value
                      - tiktok
                    -
                      - default
                      - false
  defaults: null
  maxRows: 5
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
