columnSuffix: null
handle: videoSource
instructions: null
name: Source
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Vimeo
        -
          - value
          - vimeo
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
