dateModified: 1699994958
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - link
      type: native
    -
      key: singles
      type: native
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_REPLY_TO
  template: null
  transportSettings:
    host: $EMAIL_HOSTNAME
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  fileSystemsDocuments:
    hasUrls: true
    name: Documents
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET_DOCS
      bucketSelectionMode: manual
      cfDistributionId: $S3_DOCS_DIST_ID
      cfPrefix: $S3_BUCKET_SUBFOLDER
      expires: '1 years'
      keyId: $S3_USER_ID
      makeUploadsPublic: false
      region: $S3_BUCKET_REGION
      secret: $S3_USER_SECRET
      storageClass: ''
      subfolder: $S3_BUCKET_SUBFOLDER
    type: craft\awss3\Fs
    url: $S3_DOCS_URL
  fileSystemsImages:
    hasUrls: true
    name: Images
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET_IMAGES
      bucketSelectionMode: manual
      cfDistributionId: ''
      cfPrefix: ''
      expires: '1 years'
      keyId: $S3_USER_ID
      makeUploadsPublic: false
      region: $S3_BUCKET_REGION
      secret: $S3_USER_SECRET
      storageClass: ''
      subfolder: $S3_BUCKET_SUBFOLDER
    type: craft\awss3\Fs
    url: $S3_IMAGES_URL
meta:
  __names__:
    7d923ca0-fc68-4351-98ec-1274de3906db: Home # Home
    9b18697d-2ce6-492b-b628-1a649bb22eaa: 'SEO Open Graph Image' # SEO Open Graph Image
    228f18ac-b71c-4021-8f66-0d34f29a880f: 'SEO global' # SEO global
    0499bd9f-6aa1-4590-9c16-e86191e0a2b8: Home # Home
    00548086-7b2f-44f0-a0e4-c9d91fcaae9e: Images # Images
    a7870a18-8ec8-42bd-bb94-ea232c8eb066: SEO # SEO
    b4a35b8a-1eff-4137-817a-17e468158aed: 'Public Schema' # Public Schema
    c1436119-37a0-4b5b-9538-52c47b611fd2: $SITE_GROUP # $SITE_GROUP
    ca2a274d-ce21-46a0-81e5-cd4dba43a25a: Documents # Documents
    d3974314-8390-48bd-af85-f938616558be: 'SEO Description' # SEO Description
    fc2cb4bb-e016-46f9-a830-653496da88d7: English # English
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  switcher:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: $CRAFT_SYSTEM_STATUS
  name: $CRAFT_SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Toronto
