dateModified: 1748364785
email:
  fromEmail: $EMAIL_SYSTEM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_REPLY_TO
  template: null
  transportSettings:
    host: $EMAIL_HOSTNAME
    password: $EMAIL_PASSWORD
    port: $EMAIL_PORT
    useAuthentication: '1'
    username: $EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  fileSystemsAssetTransforms:
    hasUrls: true
    name: 'Asset transforms'
    settings:
      path: '@webroot/asset-transforms'
    type: craft\fs\Local
    url: '@web/asset-transforms'
  fileSystemsDocuments:
    hasUrls: true
    name: Documents
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET_DOCS
      bucketSelectionMode: manual
      cfDistributionId: $S3_DOCS_DIST_ID
      cfPrefix: $S3_BUCKET_SUBFOLDER
      expires: '1 years'
      keyId: $S3_USER_ID
      makeUploadsPublic: false
      region: $S3_BUCKET_REGION
      secret: $S3_USER_SECRET
      storageClass: ''
      subfolder: $S3_BUCKET_SUBFOLDER
    type: craft\awss3\Fs
    url: $S3_DOCS_URL
  fileSystemsImages:
    hasUrls: true
    name: Images
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: $S3_BUCKET_IMAGES
      bucketSelectionMode: manual
      cfDistributionId: ''
      cfPrefix: ''
      expires: '1 years'
      keyId: $S3_USER_ID
      makeUploadsPublic: false
      region: $S3_BUCKET_REGION
      secret: $S3_USER_SECRET
      storageClass: ''
      subfolder: $S3_BUCKET_SUBFOLDER
    type: craft\awss3\Fs
    url: $S3_IMAGES_URL
meta:
  __names__:
    2491b9cf-e5fb-4d22-91ac-5ae6bcf8562d: Images # Images
    8517b590-fce4-474f-b972-a09fb64cd116: Français # Français
    cce026c1-81f4-4544-b9d1-42b792810a5e: Documents # Documents
    eae966b9-c034-46cf-8e92-dd12ebfba113: English # English
    f91e6549-b58b-4a20-afb6-ff84428c0ccc: $SITE_GROUP # $SITE_GROUP
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  retour:
    edition: standard
    enabled: false
    licenseKey: 639TX5GD2A1KQG4QRDDA97JC
    schemaVersion: 3.0.12
  switcher:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: $CRAFT_SYSTEM_STATUS
  name: $CRAFT_SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.7.0.3
  timeZone: $CRAFT_SYSTEM_TIMEZONE
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
