fieldLayouts:
  ee1c6b87-b3b5-4dff-ad80-5f67ec852520:
    tabs:
      -
        elements:
          -
            fieldUid: d3974314-8390-48bd-af85-f938616558be # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9b18697d-2ce6-492b-b628-1a649bb22eaa # SEO Open Graph Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 1
handle: globalSeo
name: 'SEO global'
sortOrder: 1
